language: go
go:
  - 1.3.1
env:
  - APT_GET='apt-get --option=Dpkg::Options::=--force-confold --option=Dpkg::options::=--force-unsafe-io --assume-yes --quiet'
before_install:
  - sudo add-apt-repository -y ppa:kalakris/cmake # install newer cmake
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test # install newer gcc
  - sudo $APT_GET update
  - sudo $APT_GET install mercurial git subversion cmake gcc-4.8 g++-4.8
  - export CXX=g++-4.8 CC=gcc-4.8
install:
  - ./update_llvm.sh
script:
  - go test -v
notifications:
  email:
    recipients:
      - axwalk@gmail.com
    on_success: change
    on_failure: always
